version: '3.5'

services:

  web:
    build:
      context: ./build-docker/web/
      dockerfile: Dockerfile
    container_name: web
    links:
      - postgres
    environment:
      - PYTHONPATH=${PYTHONPATH}
      - PROJ_LIB=${PROJ_LIB}
    image: "climatestation/web:1.0"
    ports:
    - 8080:80
    restart: unless-stopped
    volumes: 
    - ./log/web:/var/log/apache2
    - ./src:/var/www/climatestation:rw
    - ${DATA_VOLUME}:/data:rw
    - ${CS_VOLUME}:/climatestation:rw
    - ${TMP_VOLUME}:/tmp/climatestation:rw

  mapserver:
    build:
      context: ./build-docker/mapserver/
      dockerfile: Dockerfile
    container_name: mapserver
    image: "climatestation/mapserver:1.0"
    restart: unless-stopped
    volumes:
    - ./log/mapserver:/var/log/apache2

  postgres:
    build:
      context: ./
      dockerfile: ./build-docker/postgres/Dockerfile
    container_name: postgres
    environment:
      PGPASSWORD: "${PG_PASS}"
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_PASS: "${PG_PASS}"
      POSTGRES_DBNAME: "estationdb"
      POSTGRES_PORT: "5432"
      DEFAULT_ENCODING: "UTF8"
      DEFAULT_COLLATION: "en_US.UTF-8"
      DEFAULT_CTYPE: "en_US.UTF-8"
      POSTGRES_MULTIPLE_EXTENSIONS: "postgis,adminpack,postgis_topology"
      POSTGRES_TEMPLATE_EXTENSIONS: "true"
      WAL_SIZE: "4GB"
      MIN_WAL_SIZE: "2048MB"
      WAL_SEGSIZE: "1024"
      MAINTAINANCE_WORK_MEM: "128MB"
      DB_VERSION: "${DB_VERSION}"
    image: "climatestation/postgis:12"
    ports:
    - 5432:5432
    restart: unless-stopped
    volumes:
    - ${DBDUMP_VOLUME}:/climatestation/db_dump:rw
    - ${CS_VOLUME}:/climatestation:rw
    - ./src:/var/www/climatestation:rw
    - docker-postgresql12-volume:/var/lib/postgresql:rw
    - ./log/postgres:/var/log/climatestation:rw

# create an external docker volume: docker volume create --name cs-docker-postgresql12-volume -d local
volumes:
  docker-postgresql12-volume:
    external: true
